CREATE DATABASE doingsdone
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE doingsdone;

CREATE TABLE `categories` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    can_name VARCHAR(128) NOT NULL UNIQUE,
    user_id INT UNSIGNED NOT NULL
);

CREATE TABLE `tasks` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    publish_date DATE NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL,
    file_url VARCHAR(255),
    expire_date DATE NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    category_id INT UNSIGNED NOT NULL
);

CREATE TABLE `users` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(128) NOT NULL,
    name VARCHAR(32) NOT NULL,
    password VARCHAR(128) NOT NULL
);
